name: Feature Request
description: Propose a new feature for Laravel Intelephense
labels: ["Feature Request"]
title: "[Feature Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Laravel Intelephense likes feature requests!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
    validations:
      required: true
