'use strict';

import { Snippet } from '../laravel';

export const directives: Array<Snippet> = [
    {
        label: "@session('key')",
        version: '10.38.0',
        detail: '',
        doc: '',
        snippet: '@session(${1})\n \t ${2}{{ $value }}\n @endsession',
    },
    {
        label: '@use(namespace, optional alias)',
        version: '10.35.0',
        detail: '',
        doc: '',
        snippet: '@use(${1}, ${2})\n',
    },
    {
        label: '@pushIf(condition, stack)',
        version: '10.32.1',
        detail: '',
        doc: '',
        snippet: '@pushIf(${1}, ${2})\n \t ${3}\n @endpushIf',
    },
    {
        label: '@pushIf(condition, stack) ... @elsePush(stack) ... @pushEndIf',
        version: '10.32.1',
        detail: '',
        doc: '',
        snippet: '@pushIf(${1}, ${2})\n \t ${3}\n @elsePush(${4})\n\t${5}\n @pushEndIf',
    },
    {
        label: '@pushIf(condition, stack) ... @elsePushIf(condition, stack) ... @elsePush(stack) ... @pushEndIf',
        version: '10.32.1',
        detail: '',
        doc: '',
        snippet: '@pushIf(${1}, ${2})\n \t ${3}\n @elsePushIf(${4}, ${5})\n${6}\n @elsePush(${7})\n\t${8}\n @pushEndIf',
    },
    {
        label: '@style( ... )',
        version: '9.50.0',
        detail: '',
        doc: '@style()',
        snippet: '@style(${1})',
    },
    {
        label: '@vite( ... )',
        version: '9.19.0',
        detail: '',
        doc: '',
        snippet: '@vite(${1})',
    },
    {
        label: '@viteReactRefresh',
        version: '9.19.0',
        detail: '',
        doc: '',
        snippet: '@viteReactRefresh',
    },
    {
        label: '@required(...)',
        version: '9.20.0',
        detail: '',
        doc: '',
        snippet: '@required(${1})',
    },
    {
        label: '@disabled( ... )',
        version: '9.0.2',
        detail: '',
        doc: '@disabled()',
        snippet: '@disabled(${1})',
    },
    {
        label: '@js(...)',
        version: '8.71.0',
        detail: '',
        doc: '',
        snippet: '@js(${1})',
    },
    {
        label: '@aware(...)',
        version: '8.64.0',
        detail: '',
        doc: '',
        snippet: '@aware(${1})',
    },
    {
        label: '@class(...)',
        version: '8.51.0',
        detail: '',
        doc: '',
        snippet: '@class(${1})',
    },
    {
        label: '@sectionMissing(...)',
        version: '7.22.0',
        detail: '',
        doc: '',
        snippet: '@sectionMissing(${1})\n \t ${2}\n @endif',
    },
    {
        label: '@production',
        version: '7.11.0',
        detail: '',
        doc: '',
        snippet: '@production\n \t ${1}\n @endproduction',
    },
    {
        label: '@endproduction',
        version: '7.11.0',
        detail: '',
        doc: '',
        snippet: '@endproduction',
    },
    {
        label: '@env(...)',
        version: '7.11.0',
        detail: '',
        doc: '',
        snippet: '@env(${1})\n \t ${2}\n @endenv',
    },
    {
        label: '@endenv',
        version: '7.11.0',
        detail: '',
        doc: '',
        snippet: '@endenv',
    },
    {
        label: '@includeUnless(...)',
        version: '6.5.1',
        detail: '',
        doc: '',
        snippet: '@includeUnless(${1}, ${2})',
    },
    {
        label: '@endcomponentFirst',
        version: '5.8.24',
        detail: '',
        doc: '',
        snippet: '@endcomponentFirst',
    },
    {
        label: '@componentFirst',
        version: '5.8.22',
        detail: '',
        doc: '',
        snippet: '@componentFirst',
    },
    {
        label: '@error(...)',
        version: '5.8.13',
        detail: '',
        doc: '',
        snippet: '@error(${1})\n \t ${2}\n @enderror',
    },
    {
        label: '@enderror',
        version: '5.8.13',
        detail: '',
        doc: '',
        snippet: '@enderror',
    },
    {
        label: '@canany(...)',
        version: '5.6.23',
        detail: '',
        doc: '',
        snippet: '@canany(${1})\n \t ${2}\n @endcanany',
    },
    {
        label: '@elsecanany(...)',
        version: '5.6.23',
        detail: '',
        doc: '',
        snippet: '@elsecanany(${1})\n',
    },
    {
        label: '@endcanany',
        version: '5.6.23',
        detail: '',
        doc: '',
        snippet: '@endcanany',
    },
    {
        label: '@dump(...)',
        version: '5.6.8',
        detail: '',
        doc: '',
        snippet: '@dump(${1})',
    },
    {
        label: '@csrf',
        version: '5.6.0',
        detail: '',
        doc: '',
        snippet: '@csrf',
    },
    {
        label: '@method(...)',
        version: '5.6.0',
        detail: '',
        doc: '',
        snippet: '@method(${1})',
    },
    {
        label: '@includeFirst(...)',
        version: '5.5.5',
        detail: '',
        doc: '',
        snippet: '@includeFirst(${1})',
    },
    {
        label: '@json(...)',
        version: '5.5.3',
        detail: '',
        doc: '',
        snippet: '@json(${1})',
    },
    {
        label: '@break',
        version: '5.5.0',
        detail: '',
        doc: '@break',
        snippet: '@break',
    },
    {
        label: '@break(...)',
        version: '5.5.0',
        detail: '',
        doc: '',
        snippet: '@break(${1})',
    },
    {
        label: '@case(...)',
        version: '5.5.0',
        detail: '',
        doc: '',
        snippet: '@case(${1})\n \t ${2}\n @break',
    },
    {
        label: '@default',
        version: '5.5.0',
        detail: '',
        doc: '',
        snippet: '@default',
    },
    {
        label: '@switch(...)',
        version: '5.5.0',
        detail: '',
        doc: '',
        snippet: '@switch(${1})\n \t @case(${2})\n\t\t${3}\n\t\t@break\n\n\t@default\n\t\t${4}\n @endswitch',
    },
    {
        label: '@endswitch',
        version: '5.5.0',
        detail: '',
        doc: '',
        snippet: '@endswitch',
    },
    {
        label: '@auth',
        version: '5.4.29',
        detail: 'display a portion of the page only if the user is authorized.',
        doc: '@auth \n\n @endauth',
        snippet: '@auth\n \t ${1}\n @endauth',
    },
    {
        label: '@auth(...)',
        version: '5.4.29',
        detail: '',
        doc: '@auth() \n\n @endauth',
        snippet: '@auth(${1})\n \t ${2}\n @endauth',
    },
    {
        label: '@endauth',
        version: '5.4.29',
        detail: '',
        doc: '',
        snippet: '@endauth',
    },
    {
        label: '@guest',
        version: '5.4.29',
        detail: '',
        doc: '',
        snippet: '@guest\n \t ${1}\n @endguest',
    },
    {
        label: '@guest(...)',
        version: '5.4.29',
        detail: '',
        doc: '',
        snippet: '@guest(${1})\n \t ${2}\n @endguest',
    },
    {
        label: '@endguest',
        version: '5.4.29',
        detail: '',
        doc: '',
        snippet: '@endguest',
    },
    {
        label: '@isset(...)',
        version: '5.4.16',
        detail: '',
        doc: '',
        snippet: '@isset(${1})\n \t ${2}\n @endisset',
    },
    {
        label: '@endisset',
        version: '5.4.16',
        detail: '',
        doc: '',
        snippet: '@endisset',
    },
    {
        label: '@can(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@can(${1})\n \t ${2}\n @endcan',
    },
    {
        label: '@cannot(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@cannot(${1})\n \t ${2}\n @endcannot',
    },
    {
        label: '@checked( ... )',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@checked(${1})',
    },
    {
        label: '@continue',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@continue',
    },
    {
        label: '@continue(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@continue(${1})',
    },
    {
        label: '@component(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@component(${1})\n \t ${2}\n @endcomponent',
    },
    {
        label: '@dd(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@dd(${1})',
    },
    {
        label: '@each(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@each(${1}, ${2}, ${3})',
    },
    {
        label: '@else',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@else',
    },
    {
        label: '@elsecan(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@elsecan(${1})',
    },
    {
        label: '@elsecannot(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@elsecannot(${1})',
    },
    {
        label: '@elseif (...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@elseif (${1})',
    },
    {
        label: '@empty',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@empty',
    },
    {
        label: '@empty(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@empty(${1})\n \t ${2}\n @endempty',
    },
    {
        label: '@endcomponent',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endcomponent',
    },
    {
        label: '@endcan',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endcan',
    },
    {
        label: '@endcannot',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endcannot',
    },
    {
        label: '@endempty',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endempty',
    },
    {
        label: '@endfor',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endfor',
    },
    {
        label: '@endforeach',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endforeach',
    },
    {
        label: '@endforelse',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endforelse',
    },
    {
        label: '@endif',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endif',
    },
    {
        label: '@endonce',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endonce',
    },
    {
        label: '@endphp',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endphp',
    },
    {
        label: '@endprepend',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endprepend',
    },
    {
        label: '@endpush',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endpush',
    },
    {
        label: '@endsection',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endsection',
    },
    {
        label: '@endslot',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endslot',
    },
    {
        label: '@endunless',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endunless',
    },
    {
        label: '@endverbatim',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endverbatim',
    },
    {
        label: '@endwhile',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@endwhile',
    },
    {
        label: '@extends(...)',
        version: '0.0.0',
        detail: 'extends view layout',
        doc: '@extends()',
        snippet: '@extends(${1})',
    },
    {
        label: '@for(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@for (${1})\n \t ${2}\n @endfor',
    },
    {
        label: '@foreach(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@foreach (${1} as ${2})\n \t ${3}\n @endforeach',
    },
    {
        label: '@forelse(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@forelse (${1} as ${2})\n \t ${3}\n @empty\n\t${4}\n @endforelse',
    },
    {
        label: '@hasSection(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@hasSection(${1})\n \t ${2}\n @endif',
    },
    {
        label: '@if(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@if (${1})\n \t ${2}\n @endif',
    },
    {
        label: '@if(...) ... @else ... @endif',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@if (${1})\n \t ${2}\n @else\n\t${3}\n @endif',
    },
    {
        label: '@include(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@include(${1})',
    },
    {
        label: '@includeIf(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@includeIf(${1})',
    },
    {
        label: '@includeWhen(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@includeWhen(${1}, ${2})',
    },
    {
        label: '@inject(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@inject(${1}, ${2})',
    },
    {
        label: '@lang(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@lang(${1})',
    },
    {
        label: '@once',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@once\n \t ${1}\n @endonce',
    },
    {
        label: '@parent',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@parent',
    },
    {
        label: '@php',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@php\n \t ${1}\n @endphp',
    },
    {
        label: '@prepend(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@prepend(${1})\n \t ${2}\n @endprepend',
    },
    {
        label: '@props(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@props(${1})',
    },
    {
        label: '@push(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@push(${1})\n \t ${2}\n @endpush',
    },
    {
        label: '@readonly(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@readonly(${1})',
    },
    {
        label: '@section(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@section(${1})',
    },
    {
        label: '@section(...) ... @endsection',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@section(${1})\n \t ${2}\n @endsection',
    },
    {
        label: '@selected(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@selected(${1})',
    },
    {
        label: '@show',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@show',
    },
    {
        label: '@slot(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@slot(${1})',
    },
    {
        label: '@stack(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@stack(${1})',
    },
    {
        label: '@stop',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@stop',
    },
    {
        label: '@unless(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@unless (${1})\n \t ${2}\n @endunless',
    },
    {
        label: '@verbatim ...',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@verbatim\n \t ${2}\n @endverbatim',
    },
    {
        label: '@while(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@while (${1})\n \t ${2}\n @endwhile',
    },
    {
        label: '@yield(...)',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: '@yield(${1})',
    },
];

