'use strict';

import { Snippet } from '../laravel';

export const validationRules: Array<Snippet> = [
    {
        label: 'hex_color',
        version: '10.33.0',
        detail: '',
        doc: '',
        snippet: 'hex_color',
    },
    {
        label: 'present_if',
        version: '10.32.0',
        detail: '',
        doc: '',
        snippet: 'present_if:${1:attribute},${2:value}',
    },
    {
        label: 'present_with',
        version: '10.32.0',
        detail: '',
        doc: '',
        snippet: 'present_with:${1:attribute}',
    },
    {
        label: 'present_unless',
        version: '10.32.0',
        detail: '',
        doc: '',
        snippet: 'present_unless:${1:attribute},${2:value}',
    },
    {
        label: 'present_with_all',
        version: '10.32.0',
        detail: '',
        doc: '',
        snippet: 'present_with_all:${1:attribute1},${2:attribute2}',
    },
    {
        label: 'timezone_param',
        version: '10.12.0',
        detail: '',
        doc: '',
        snippet: 'timezone:${1:value}',
    },
    {
        label: 'missing',
        version: '9.49.0',
        detail: '',
        doc: '',
        snippet: 'missing:${1:value}',
    },
    {
        label: 'missing_if',
        version: '9.49.0',
        detail: '',
        doc: '',
        snippet: 'missing_if:${1:attribute},${2:value}',
    },
    {
        label: 'missing_unless',
        version: '9.49.0',
        detail: '',
        doc: '',
        snippet: 'missing_unless:${1:attribute},${2:value}',
    },
    {
        label: 'missing_with',
        version: '9.49.0',
        detail: '',
        doc: '',
        snippet: 'missing_with:${1:attribute1},${2:attribute2}',
    },
    {
        label: 'missing_with_all',
        version: '9.49.0',
        detail: '',
        doc: '',
        snippet: 'missing_with_all:${1:attribute1},${2:attribute2}',
    },
    {
        label: 'decimal',
        version: '9.45.0',
        detail: '',
        doc: '',
        snippet: 'decimal:${1:min},${2:max}',
    },
    {
        label: 'ulid',
        version: '9.44.0',
        detail: '',
        doc: '',
        snippet: 'ulid',
    },
    {
        label: 'ascii',
        version: '9.44.0',
        detail: '',
        doc: '',
        snippet: 'ascii',
    },
    {
        label: 'lowercase',
        version: '9.40.0',
        detail: '',
        doc: '',
        snippet: 'lowercase',
    },
    {
        label: 'uppercase',
        version: '9.40.0',
        detail: '',
        doc: '',
        snippet: 'uppercase',
    },
    {
        label: 'min_digits',
        version: '9.26.0',
        detail: '',
        doc: '',
        snippet: 'min_digits:${1:value}',
    },
    {
        label: 'max_digits',
        version: '9.26.0',
        detail: '',
        doc: '',
        snippet: 'max_digits:${1:value}',
    },
    {
        label: 'accepted',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'accepted',
    },
    {
        label: 'active_url',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'active_url',
    },
    {
        label: 'after',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'after:date',
    },
    {
        label: 'after_or_equal',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'after_or_equal:${0:date}',
    },
    {
        label: 'alpha',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'alpha',
    },
    {
        label: 'alpha_dash',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'alpha_dash',
    },
    {
        label: 'alpha_num',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'alpha_num',
    },
    {
        label: 'array',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'array',
    },
    {
        label: 'bail',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'bail',
    },
    {
        label: 'before',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'before:${1:date}',
    },
    {
        label: 'before_or_equal',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'before_or_equal:${1:date}',
    },
    {
        label: 'between',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'between:${1:min},${2:max}',
    },
    {
        label: 'boolean',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'boolean',
    },
    {
        label: 'confirmed',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'confirmed',
    },
    {
        label: 'date',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'date',
    },
    {
        label: 'date_equals',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'date_equals:${1:date}',
    },
    {
        label: 'date_format',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'date_format:${1:format}',
    },
    {
        label: 'different',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'different:${1:field}',
    },
    {
        label: 'digits',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'digits:${1:value}',
    },
    {
        label: 'digits_between',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'digits_between:${1:min},${2:max}',
    },
    {
        label: 'dimensions',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'dimensions',
    },
    {
        label: 'distinct',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'distinct',
    },
    {
        label: 'email',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'email',
    },
    {
        label: 'ends_with',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'ends_with:${1}',
    },
    {
        label: 'exists',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'exists:${2:table},${3:column}',
    },
    {
        label: 'file',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'file',
    },
    {
        label: 'filled',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'filled',
    },
    {
        label: 'gt',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'gt:${1:field}',
    },
    {
        label: 'gte',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'gte:${1:field}',
    },
    {
        label: 'image',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'image',
    },
    {
        label: 'in',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'in:${1:something},${2:something else}',
    },
    {
        label: 'in_array',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'in_array:${1:anotherField.*}',
    },
    {
        label: 'integer',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'integer',
    },
    {
        label: 'ip',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'ip',
    },
    {
        label: 'ipv4',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'ipv4',
    },
    {
        label: 'ipv6',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'ipv6',
    },
    {
        label: 'json',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'json',
    },
    {
        label: 'lt',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'lt:${1:field}',
    },
    {
        label: 'lte',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'lte:${1:field}',
    },
    {
        label: 'max',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'max:${1:value}',
    },
    {
        label: 'mimetypes',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'mimetypes:${1:text/plain}',
    },
    {
        label: 'mimes',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'mimes:${1:png,jpg}',
    },
    {
        label: 'min',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'min:${1:value}',
    },
    {
        label: 'not_in',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'not_in:${1:something},${2:something else}',
    },
    {
        label: 'not_regex',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'not_regex:${1:pattern}',
    },
    {
        label: 'nullable',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'nullable',
    },
    {
        label: 'numeric',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'numeric',
    },
    {
        label: 'present',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'present',
    },
    {
        label: 'regex',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'regex:${1:pattern}',
    },
    {
        label: 'required',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'required',
    },
    {
        label: 'required_if',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'required_if:${1:anotherField},${2:value}',
    },
    {
        label: 'required_unless',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'required_unless:${1:anotherField},${2:value}',
    },
    {
        label: 'required_with',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'required_with:${1:anotherField}',
    },
    {
        label: 'required_with_all',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'required_with_all:${1:anotherField},${2:anotherField}',
    },
    {
        label: 'required_without',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'required_without:${1:anotherField}',
    },
    {
        label: 'required_without_all',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'required_without_all:${1:anotherField},${2:anotherField}',
    },
    {
        label: 'same',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'same:${1:field}',
    },
    {
        label: 'size',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'size:${1:value}',
    },
    {
        label: 'sometimes',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'sometimes',
    },
    {
        label: 'starts_with',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'starts_with:${1:foo},${2:bar}',
    },
    {
        label: 'string',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'string',
    },
    {
        label: 'timezone',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'timezone',
    },
    {
        label: 'unique',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'unique:${1:table},${2:column},${3:except},${4:id}',
    },
    {
        label: 'url',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'url',
    },
    {
        label: 'uuid',
        version: '0.0.0',
        detail: '',
        doc: '',
        snippet: 'uuid',
    },
];
